name: dotnet_1 CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  run-ci:
    uses: CarterPham/Template/.github/workflows/dotnet_ci.yml@main
    with:
      project_path: 'SingleFileConsoleApp.csproj'
      project_name: 'dotnet_1'

  run-cd:
    needs: run-ci
    uses: CarterPham/Template/.github/workflows/dotnet_cd.yml@main
    with:
      project_name: 'dotnet_1'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# comment