name: dotnet_1 CI/CD

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  run-ci:
    # Points to your central DevOps repo
    uses: CarterPham/Template.git/.github/workflows/Dotnet_ci.yml@master
    
    with:
      project_path: 'SingleFileConsoleApp.csproj'
      project_name: 'dotnet_1'

  run-cd:
    needs: run-ci
    uses: CarterPham/Template.git/.github/workflows/Dotnet_cd.yml@master
    with:
      project_name: 'dotnet_1'
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}